icon:
  default: ''
  description: Choose the source icon and the destination icon in this way, user, fab-android
svg_icons: 
  default: ''
  type: list
  description: Additional FontAwesome 5 icons used in this theme
